import '../globals.css';
import SessionWrapper from '../SessionWrapper';
import LayoutWrapper from '../../component/LayoutWrapper';
import { getDictionary } from '@/lib/getDictionary';
import TranslationsProvider from '@/lib/TranslationsProvider';
import { Poppins, Inter } from "next/font/google";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-inter",
});


// ✅ Static Params for SSG
export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'fr' }, { lang: 'de' }];
}

// ✅ Layout Component
export default async function RootLayout({ children, params }) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang);
  const isRTL = ['ar', 'fa', 'he'].includes(lang); // right-to-left support

  return (
    <html lang={lang} dir={isRTL ? 'rtl' : 'ltr'}>
      <head>
        {/* ✅ SweetAlert2 Styles (if not already in _document.js or head) */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css"
        />
      </head>
      <body>
        {/* ✅ Provide translation and session to entire app */}
        <TranslationsProvider dictionary={dictionary} locale={lang}>
          <SessionWrapper>
            <LayoutWrapper>{children}</LayoutWrapper>
          </SessionWrapper>
        </TranslationsProvider>
      </body>
    </html>
  );
}
