// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Navbar from "../component/usercomponent/navbar/Navbar";
import Footer from "../component/usercomponent/footer/Footer";
// src/app/layout.js or layout.jsx
import 'bootstrap/dist/css/bootstrap.min.css';
import LayoutWrapper from "../component/LayoutWrapper"
import SessionWrapper from "./SessionWrapper";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ SweetAlert2 CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css"
        />
      </head>
      <body>
      <SessionWrapper>
        <LayoutWrapper>{children}</LayoutWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}